// reactfront/src/App.tsx
import React, { useState } from "react";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import "./App.css";
import "./Style.css";
import Consult_Question from "./consultant/Consult_Question";
import User_Dash from "./admin/User_Dash";
import Consultant_Dash from "./admin/Consultant_Dash";
import ConsultantProfile from "./consultant-profile/ConsultantProfile";
import OTO_detail from "./OneToOne/OTO_detail";
import OTO_main from "./OneToOne/OTO_main";
import Feedback from "./feedback/feedback";
import FeedbackDetail from "./feedback/feedbackDetail";

import ConsultantAdmin from "./admin-consultant/ConsultantAdmin";
import MemberList from "./admin/member/MemberList";
import MemberModal from "./admin/member/MemberModal";


const App: React.FC = () => {
  const [isSidebarVisible, setIsSidebarVisible] = useState(true);

  const toggleSidebar = () => {
    setIsSidebarVisible(!isSidebarVisible);
  };

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  return (
    <Router>
      <div id="app">
        <Header toggleSidebar={toggleSidebar} />
        <i className="bi bi-list fixed-menu-icon" onClick={toggleSidebar}></i>
        <Sidebar isVisible={isSidebarVisible} />
        <main
          className={`main-content ${isSidebarVisible ? "sidebar-open" : ""}`}
        >
          <Routes>
            {/* User DashBoard */}
            <Route path="/admin/User_Dash" element={<User_Dash />} />

            {/* Consultant DashBoard */}
            <Route path="/admin/Consultant_Dash" element={<Consultant_Dash />} />

            {/* Member Admin DashBoard */}
            <Route path="/member/MemberList" element={<MemberList />} />

            {/* Consultant Admin */}
            <Route path="/admin-consultant/ConsultantAdmin" element={<ConsultantAdmin />} />

            {/*<Route path="/mypage" element={<YourMypageComponent />} />
            <Route path="/InterviewRes" element={<YourInterviewResComponent />} /> */}

            {/* ConsultantProfile */}
            <Route
              path="/consultant/consultant-profile"
              element={<ConsultantProfile />}
            />

            {/* Consult_Question */}
            <Route
              path="/consultant/Consult_Question"
              element={<Consult_Question />}
            />

            {/* OneToOne */}
            <Route path="/consultant/OneToOne" element={<OTO_main />} />
            <Route
              path="/consultant/OneToOne/detail"
              element={<OTO_detail />}
            />

            {/* feedback */}
            <Route path="/consultant/feedback" element={<Feedback />} />
            <Route
              path="/consultant/feedback/detail"
              element={<FeedbackDetail />}
            />
          </Routes>
        </main>
        <i className="bi bi-caret-up scroll-to-top" onClick={scrollToTop}>
          <p style={{ display: "inline", fontSize: "20px" }}>TOP</p>
        </i>
        <Footer />
      </div>
    </Router>
  );
};

export default App;

// vuefront/src/App.vue
<template>
  <div id="app">
    <Header
      @toggle-sidebar="toggleSidebar"
      :class="{'main-header': true, 'sidebar-open': isSidebarVisible}"
    />
    <i class="bi bi-list fixed-menu-icon" @click="toggleSidebar"></i>
    <Sidebar :isVisible="isSidebarVisible" />
    <main :class="{'main-content': true, 'sidebar-open': isSidebarVisible}">
      <router-view :isSidebarVisible="isSidebarVisible" :setSidebarVisibility="setSidebarVisibility"/>
    </main>
    <i class="bi bi-caret-up scroll-to-top" @click="scrollToTop"><p style="display:inline; font-size:20px">TOP</p></i>
    <Footer/>
  </div>
</template>

<script>
import Footer from './components/Footer.vue'
import Header from './components/Header.vue'
import Sidebar from './components/Sidebar.vue'

export default {
  components: { Header, Footer, Sidebar },
  data() {
    return {
      isSidebarVisible: true,
    };
  },
  methods: {
    toggleSidebar() {
      this.isSidebarVisible = !this.isSidebarVisible;
    },
    setSidebarVisibility(isVisible) {
      this.isSidebarVisible = isVisible;
    },
    scrollToTop() {
      window.scrollTo({
        top: 0,
        behavior: 'smooth'
      });
    },
  },
}
</script>

<style>
html, body {
  overflow-x: hidden;
}
#app {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 0;
  min-height: 100vh;
  background: #0c1b49 no-repeat center center fixed;
  background-size: cover;
}
</style>
